#ifndef Constant_h
#define Constant_h

#include <FastLED.h>

#define DEBUG_MODE 1
#define CLEAN_MODE -1
#define DETAILS_MODE 1
#define CURRENT_MODE DEBUG_MODE +1
#define SLEEP_SONG 5
/*
#define VOLUME_PIN 15
#define MP3_RX_PIN 16
#define MP3_TX_PIN 17
#define SENSOR_PIN 23
*/
#define VOLUME_PIN 34
#define MP3_RX_PIN 18
#define MP3_TX_PIN 19
#define SENSOR_PIN 35

// Buttons Signals
#define BUTTON_MUSIC 34
#define BUTTON_MUTE 34
#define BUTTON_LED_SEQUENCE 34
#define BUTTON_STEPPER 34
#define BUTTON_SLEEPING 34

#define BUTTON_SETTINGS 34
#define BUTTON_ARROW_LEFT 34
#define BUTTON_ARROW_RIGHT 34

#define BUTTON_ARROW_UP 34
#define BUTTON_ARROW_DOWN 34

#define BUTTON_CONTROLS_DELTA_TIME 300
#define BUTTON_PRESSED HIGH

// Stepper
#define STEPPER_INCREMENT 1
#define STEPPER_RPM 5
#define STEPPER_IN_1 25
#define STEPPER_IN_2 33
#define STEPPER_IN_3 32
#define STEPPER_IN_4 13
#define STEPS_PER_REVOLUTION 4096
#define STEPPER_DELTA_TIME 80


// DELAYS
#define SETUP_DELAY 2000
#define DELAY_SOFT_START_SLEEP 5000
#define DELAY_AFTER_SONG 10000
#define DELAY_AFTER_HELLO 10000

//#define SLEEP_SHUTDOWN 600000
#define SLEEP_SHUTDOWN 60*1000

/////////////////////// Leds
#define LED_TYPE WS2812B
#define COLOR_ORDER GRB
#define BRIGHTNESS 140

// Wheel
#define WHEEL_NUM_LEDS 8
#define WHEEL_LIGHTS_DATA_PIN 14
#define PATTERN_PERIOD 12

// LED SEQUENCE TIMING
#define LIGHTS_DELAY 150
#define DELTA_RGB_LOOP 10
#define DELTA_TIME_RAINBOW 40
#define DELTA_SLEEPING_SLOW 80
#define DELTA_SLEEPING_FAST 20
#define MAX_VALUE_LIGHT_FOR_SLEEP 50
#define MIN_VALUE_LIGHT_FOR_SLEEP 5
#define SLEEP_THRESHOLD 5
#define WHEEL_LOOPS 44

// Console
#define EYES_LED_DATA_PIN 26
#define CONSOLE_LIGHTS_CONTROLLER_DATA_PIN 27

#define DELTA_TIME_CONSOLE_UPDATES 200
#define CONSOLE_LIGHTS_INTENSITY 100
#define SLEEP_LED_INTENTISY 10


// Disabled
#define ENABLED 1
#define DISABLED 0
#define CONTROL_STEPPER DISABLED
#define CONTROL_MUSIC DISABLED
#define CONTROL_DISPLAY DISABLED
#define CONTROL_BUTTON DISABLED
#define CONTROL_LIGHTS DISABLED
#define CONTROL_CONSOLE_LIGHTS DISABLED
#define CONTROL_CONSOLE DISABLED
#define CONTROL_RTC DISABLED


FASTLED_USING_NAMESPACE

#if defined(FASTLED_VERSION) && (FASTLED_VERSION < 3001000)
#warning "Requires FastLED 3.1 or later; check github for latest code."
#endif

#endif